LangString LauncherOptionsHeader ${LANG_ENGLISH} "Enter Master Password"
LangString LauncherOptionsHeader2 ${LANG_ENGLISH} "Enter your master password to allow Iron to use your saved passwords."
LangString LauncherOptionsIntro ${LANG_ENGLISH} "If this is the first time you are using the Portable Passwords system, you can choose your password now."
LangString LauncherOptionsValidate ${LANG_ENGLISH} "You must enter a password to use the Portable Passwords system!"
LangString LauncherInvalidPassword ${LANG_ENGLISH} "The provided password does not match the master password!"
LangString LauncherOptionsOK ${LANG_ENGLISH} "OK"
LangString LauncherOptionsCancel ${LANG_ENGLISH} "Cancel"
LangString LauncherDLLError ${LANG_ENGLISH} "There was a problem with Portable Passwords, so Portable Passwords has been disabled for this ${PORTABLEAPPNAME} session."
LangString LauncherShuttingDown ${LANG_ENGLISH} "${PORTABLEAPPNAME} is still busy shutting down.  Please wait for a bit before trying to launch ${PORTABLEAPPNAME} again."
